### ISSUE TITLE
Can't run it on Macos 10.13.2

### ISSUE THREAD

**Issue by FengGou** [sviehb/jefferson#10]
➜  jefferson (master) ✗ jefferson
Traceback (most recent call last):
  File "/usr/local/bin/jefferson", line 11, in <module>
    from jefferson import jffs2_lzma, rtime
  File "/Library/Python/2.7/site-packages/jefferson/jffs2_lzma.py", line 3, in <module>
    import lzma
ImportError: dlopen(/Library/Python/2.7/site-packages/lzma.so, 2): Symbol not found: _lzma_alone_encoder
  Referenced from: /Library/Python/2.7/site-packages/lzma.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/lzma.so

**Comment by pich4ya** [comment]
pip install pyliblzma cstruct

**Comment by mk2soldier** [comment]
I'm also experiencing the same issue as @FengGou, macOS 10.12.6, Python 2.7, cstruct 1.7, pyliblzma 0.5.3, jefferson 0.2

![screen shot 2018-04-28 at 10 47 20 pm](https://user-images.githubusercontent.com/5905339/39400713-25be55f6-4b36-11e8-899a-91bd3fc5a093.png)

![screen shot 2018-04-28 at 10 45 29 pm](https://user-images.githubusercontent.com/5905339/39400706-087ff17a-4b36-11e8-83b0-49b42c2dab55.png)

**Comment by betaver** [comment]
+1

![image](https://user-images.githubusercontent.com/3680241/48466800-d7fc4880-e821-11e8-9ba2-68c4630cc09a.png)

**Comment by sviehb** [comment]
Thank you. Master now uses the pylzma library. Please let me know if you find any other issues on OSX.
