### ISSUE TITLE
OverflowError: can't convert negative number to unsigned long

### ISSUE THREAD

**Issue by pich4ya** [sviehb/jefferson#11]
$ jefferson -v -f XXX.jffs2
```...
writing XXX/YYY
Traceback (most recent call last):
  File "/usr/local/bin/jefferson", line 500, in <module>
    main()
  File "/usr/local/bin/jefferson", line 495, in main
    dump_fs(fs, dest_path_fs)
  File "/usr/local/bin/jefferson", line 429, in dump_fs
    os.mknod(target_path, inode.mode, get_device(inode))
OverflowError: can't convert negative number to unsigned long
```

Solution:
I checked out the arguments but I couldn't find negative numbers on inode properties.
So I just commented out line number 429 in /usr/local/bin/jefferson
```
# os.mknod(target_path, inode.mode, get_device(inode))
```

**Comment by sviehb** [comment]
Looks like you are dealing with a somehow malformed filesystem image. Can you provide a sample?

**Comment by qkaiser** [comment]
@pich4ya did you provide a sample ? Without a sample I'll close this issue.

**Comment by qkaiser** [comment]
It's been four years without samples. Closing.
