### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AliRazaManzoor** [sviehb/jefferson#12]
jefferson use for unpack jeffs2 image so have any utility for repack image ?

**Comment by sviehb** [comment]
This is beyond what jefferson can do. However here are some resources on how to create a JFFS2 image from a directory (which could be jefferson output):
- https://linuxlink.timesys.com/docs/wiki/engineering/HOWTO_Create_JFFS2_Images
- http://manpages.ubuntu.com/manpages/focal/man1/mkfs.jffs2.1.html
