### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by ghost** [sviehb/jefferson#14]
I may update this project myself (since it is dead and I will need it).

So, python-lzma does not exist for OSX. It can be potentially replaced with pylzma (pip install pylzma).
CStruct is (sudo pip install cstruct).

Pip support drops for Python 2.7 in January 2020. If I pick up the project, I am making sure it works for Python 3 (and will not support Python 2).

I see no further complaints, but I don't have a functional jefferson yet. I can get the help output, but no successful extraction. I also only changed `import lzma` to `import pylzma` to test the import. I have other projects I have to finish first, so I cannot work on this one atm.

**Comment by MorningLightMountain713** [comment]
This pretty much works out of the box. just have to `pip install pylzma` then `import pylzma as lzma`

**Comment by sviehb** [comment]
Thank you. Master now uses the pylzma library. Please let me know if you find any other issues on OSX.
