### ISSUE TITLE
Can you create tools to extract information detail of a jffs2 filesystem? 

### ISSUE THREAD

**Issue by ykhandler** [sviehb/jefferson#26]
First of all, sorry to create this issue, because i dont know how to contact you. Your jefferson project is awesome, i can extract the jffs2 file system even in my Android phone. But i got difficulty on Recreating the jffs2 filesystem, i dont know what parameters needed to recreate it so the linux system can flash it and run/parse it normally. 
When i try to create it, the linux system seems to flash it normally  but it is writting NULL bytes at  0x2000 until 0x3000 bytes and some other, so the file in the partition is corrupt. Here is the sample:

![FlashingFailed](https://user-images.githubusercontent.com/22582826/106385427-d5866900-6402-11eb-9bbb-124d5c26eb19.png)

The only thing i can use is from the original backup of the partition, it flash normally and not writting NULL bytes. I'm still curious is it because a fault on recreating the jffs2 filesystem or there is protection on the linux system.

Here is the Original partition backup that can be use:

[m4.zip](https://github.com/sviehb/jefferson/files/5899805/m4.zip)

mtdinfo only shows the erase block size, it is 64kb, but using -e 0x1000 or -e 64 still not work. 

Thanks for your time reading my problem, i hope you can give me some solution. Thanks.,

**Comment by qkaiser** [comment]
It's not in our short-term plans to make jefferson print out meta-data about a JFFS2 filesystem.

If you want to repack extracted files into a JFFS2 filesystem that can be parsed by your device, make sure you got these `mkfs`
parameters right:

- `--pagesize`
- `--eraseblock`
- `--compr-mode`
- `-l` or `-b` for endianness
