### ISSUE TITLE
Setup.py distutils.core no module

### ISSUE THREAD

**Issue by stricklandrbls** [sviehb/jefferson#29]
> user@computer:~/git/jefferson$ sudo python3 setup.py install
> Traceback (most recent call last):
>   File "setup.py", line 4, in <module>
>     from distutils.core import setup
> ModuleNotFoundError: No module named 'distutils.core'

Successfully ran pip3 install -r requirements.txt but the setup.py spat out this error for this module. Shouldn't it try to install it from the requirements.txt as well?

**Comment by qkaiser** [comment]
The fix is to install distutils with `apt install python3-distutils`.

We will probably move to poetry and PyPi packaging in the near future so we will not edit requirements.txt or setup.py.
