### ISSUE TITLE
ImportError: No module named lzma

### ISSUE THREAD

**Issue by hillz1** [sviehb/jefferson#3]
When running `jefferson` I get the error `ImportError: No module named lzma` and when I try installing `lzma` with `sudo pip install lzma` I get:

```
Downloading/unpacking lzma
  Could not find any downloads that satisfy the requirement lzma
Cleaning up...
No distributions at all found for lzma
Storing debug log for failure in /home/galih/.pip/pip.log
```

I'm on python 2.7 how do I fix that?

**Comment by sviehb** [comment]
Python 2.7 does not come with LZMA-support. Running `sudo apt-get install python-lzma` or `sudo pip install pyliblzma` should fix the problem. I'll add it to the dependencies.

**Comment by jerryliu306** [comment]
sudo yum install xz-devel python-backports-lzma
sudo pip3 install backports.lzma

在文件 /usr/local/lib/python3.6/lzma.py line 27行 修改如下:
try:
    from _lzma import *
    from _lzma import _encode_filter_properties, _decode_filter_properties
except ImportError:
    from backports.lzma import *
    from backports.lzma import _encode_filter_properties, _decode_filter_properties
