### ISSUE TITLE
Nodes version ordering during filesystem scan

### ISSUE THREAD

**Issue by raplin** [sviehb/jefferson#32]
Excuse me if I am an idiot, but I believe JFFS2 nodes need to be sorted by the 'version' field before being applied (lowest first), and I do not see this in the code..? 
Doesn't this mean garbled output when a filesystem has been in use for a while?

**Comment by qkaiser** [comment]
You are entirely right. We will work on this in the near future.

**Comment by qkaiser** [comment]
Reference from the documentation:

> There is a total ordering between all the nodes belonging to any individual inode, which is maintained by storing a version number in each node. Each node is written with a version higher than all previous nodes belonging to the same inode. The version is an unsigned 32-bit field, allowing for 4 milliard nodes to be written for each inode during the life span of the file system. Because the limited lifetime of flash chips means this number is extremely unlikely to be reached, this limitation is deemed to be acceptable.
